In [1]:
# matrix: 행렬 만들기 
# matrix(data,행,열)
x <- matrix(1:20,5,4)
x

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [2]:
class(x)

[1] "matrix"

In [3]:
# 2행~4행, 모든열 
x[2:4,]

[,1] [,2] [,3] [,4]
[1,] 2    7    12   17  
[2,] 3    8    13   18  
[3,] 4    9    14   19

In [5]:
# 2행 제외 모든열
x[-2,]

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 3     8   13   18  
[3,] 4     9   14   19  
[4,] 5    10   15   20

In [6]:
# 2~4행 2열
x[2:4,2]

[1] 7 8 9

In [7]:
# 열부터 data 들여쓰기
matrix(1:20,4,5,byrow=TRUE)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20

In [8]:
# 배열생성
x <- array(1:2,c(5,4,2))
x

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    2    1    2
[2,]    2    1    2    1
[3,]    1    2    1    2
[4,]    2    1    2    1
[5,]    1    2    1    2

, , 2

     [,1] [,2] [,3] [,4]
[1,]    1    2    1    2
[2,]    2    1    2    1
[3,]    1    2    1    2
[4,]    2    1    2    1
[5,]    1    2    1    2

In [11]:
# list생성
x  <- list(c(1:5),c(1:50))
x

[[1]]
[1] 1 2 3 4 5

[[2]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

In [13]:
x  <- list(flower='rose',color=c('red','white'))
x

$flower
[1] "rose"

$color
[1] "red"   "white"

In [14]:
# 데이터프레임 생성
df <- data.frame(name=c('lee','kim','choi','park'),age=c(27,32,18,39),height=c(180,184,173,148))
df

name age height
1 lee  27  180   
2 kim  32  184   
3 choi 18  173   
4 park 39  148

In [15]:
df[1:3,]

name age height
1 lee  27  180   
2 kim  32  184   
3 choi 18  173

In [16]:
df[,2]

[1] 27 32 18 39

In [17]:
df[,2,drop=FALSE]

age
1 27 
2 32 
3 18 
4 39

In [20]:
rownames(df) <- c('one','two','three','four')
df

name age height
one   lee  27  180   
two   kim  32  184   
three choi 18  173   
four  park 39  148

In [21]:
df[c('one','three'),]

name age height
one   lee  27  180   
three choi 18  173

In [22]:
df[,'age']

[1] 27 32 18 39

In [23]:
df[,'age',drop=FALSE]

age
one   27 
two   32 
three 18 
four  39

# QUIZ
### P1

In [24]:
# 데이터 프레임 만들기
df=data.frame('이름'=c('민준','유리','재희'),'나이'=c(22,20,21),'성별'=c('남','여','남'),'전공'=c('수학','영문','경영'))
df

이름 나이 성별 전공
1 민준 22   남   수학
2 유리 20   여   영문
3 재희 21   남   경영

In [26]:
# 인덱스 생성
rownames(df)=c(0,1,2)
df

이름 나이 성별 전공
0 민준 22   남   수학
1 유리 20   여   영문
2 재희 21   남   경영

### P2

In [83]:
list(df[,1])

[[1]]
[1] 민준 유리 재희
Levels: 민준 유리 재희

In [84]:
list(df[,2])

[[1]]
[1] 22 20 21

In [85]:
list(df[,3])

[[1]]
[1] 남 여 남
Levels: 남 여

### P3

In [35]:
df[1,]

이름 나이 성별 전공
0 민준 22   남   수학

In [38]:
df[2,]

이름 나이 성별 전공
1 유리 20   여   영문

In [37]:
df[3,]

이름 나이 성별 전공
2 재희 21   남   경영

### P4

In [71]:
df[2:3,]

이름 나이 성별 전공
1 유리 20   여   영문
2 재희 21   남   경영

### P5

In [72]:
df[,2:3,drop=FALSE]

나이 성별
0 22   남  
1 20   여  
2 21   남

### P6

In [75]:
mean(df[,2])

[1] 21

### P7

In [96]:
df['성별']

ERROR: Error in group_by(df["성별"], ): 함수 "group_by"를 찾을 수 없습니다


In [3]:
library(tidyr)

In [8]:
library(dplyr)


Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union



In [11]:
summarise(iris,avg=mean(Sepal.Length))

avg     
1 5.843333

In [13]:
x <- read.csv('reservation_r_csv.csv') 

In [14]:
head(x)

RESERV_NO  RESERV_DATE RESERV_TIME CUSTOMER_ID BRANCH VISITOR_CNT CANCEL
1 2019082701 20190827    1800        W1340914    마포   2           N     
2 2019082602 20190826    1200        W341658     동작   5           N     
3 2019082601 20190826    1800        W1328993    강북   4           N     
4 2019082501 20190825    1800        W1340463    용산   2           N     
5 2019082401 20190824    1200        W1344912    강동   3           N     
6 2019082301 20190823    1800        W1344753    영등포 2           N